### ISSUE TITLE
CI連携

### ISSUE THREAD

**Issue by showwin** [showwin/QIDB#84]
CircleCI連携して、CIからデプロイする。
simplecovも加えて、テストカバレッジも表示する。

**Comment by showwin** [comment]
CircleCI から coverall への結果 push がうまくいかない

>[Coveralls] Submitting with config:
{"environment":{"pwd":"/home/ubuntu/QIDB","rails_root":"/home/ubuntu/QIDB","simplecov_root":"/home/ubuntu/QIDB","gem_version":"0.7.1","circleci_build_num":"7","branch":"master","commit_sha":"42c7bdf7100f4a843752f96e745f5404586b425d"},"git":{"head":{"id":"42c7bdf7100f4a843752f96e745f5404586b425d","author_name":"ITO Shogo","author_email":"showwin_kmc@yahoo.co.jp","committer_name":"ITO Shogo","committer_email":"showwin_kmc@yahoo.co.jp","message":"Merge pull request #87 from showwin/add_simplecov"},"branch":"master","remotes":[{"name":"origin","url":"git@github.com:showwin/QIDB.git"}]},"configuration":{"repo_token":"\u003c%= ENV[\"COVERALLS_TOKEN\"] %\u003e"},"repo_token":"\u003c%= ENV[\"COVERALLS_TOKEN\"] %\u003e","service_name":"circleci","service_number":"7"}
[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
RestClient::UnprocessableEntity
422 Unprocessable Entity
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:853:in `start'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/coveralls-0.7.1/lib/coveralls/api.rb:24:in `post_json'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:72:in `format'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/simplecov-0.7.1/lib/simplecov/result.rb:91:in `format!'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/simplecov-0.7.1/lib/simplecov/configuration.rb:133:in `block in at_exit'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/simplecov-0.7.1/lib/simplecov/defaults.rb:52:in `call'
/home/ubuntu/QIDB/vendor/bundle/ruby/2.1.0/gems/simplecov-0.7.1/lib/simplecov/defaults.rb:52:in `block in <top (required)>'
{"message":"Couldn't find a repository matching this job.","error":true}

**Comment by showwin** [comment]
ToDo
* [ ] Capistrano で CI からデプロイ (master ブランチをデプロイ)
* [ ] Passenger → Unicorn
* [ ] Apache → Nginx

**Comment by showwin** [comment]
7e4e9d3 のコミットで自動デプロイができるようになった
